DELETE http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbGRpbmlAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYzMDk5NDEsInVzZXJJZCI6MX0.WQozkclUoYsL7ZSlRolGRfdm1G7YvcK57Xg_aY8FCKw