POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbGRpbmlAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYzMDU1NTIsInVzZXJJZCI6MX0.FEa-EBFXtd_vtkyRS9rQsApYh9bCQuvb4DzHItXp9vQ

{
    "name": "Paris tour",
    "description": "Tour to Paris",
    "location": "Paris",
    "dateTime": "2025-04-30T15:00:00.000Z"
}