POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbGRpbmlAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYwNTM5MTMsInVzZXJJZCI6Mn0.z_tZ4KQzlCRFvx4jHmQNaVnh8N0rFdJOwyxDhgYzQEk

{
    "name": "Paris tour",
    "description": "Tour to Paris",
    "location": "Paris",
    "dateTime": "2025-04-30T15:00:00.000Z"
}