POST http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbGRpbmlAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYzMDU1NTIsInVzZXJJZCI6MX0.FEa-EBFXtd_vtkyRS9rQsApYh9bCQuvb4DzHItXp9vQ